Rename array.md to arrays.md
In the `package.xml` file we have `arrays.md` instead of `array.md`: that breaks the compilation with pecl:

ERROR: file /path/to/phpredis/arrays.md does not exist